// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/ProductBuildersHQ/prism-control/ent/assignment"
	"github.com/ProductBuildersHQ/prism-control/ent/deliveryevidence"
	"github.com/ProductBuildersHQ/prism-control/ent/initiative"
	"github.com/ProductBuildersHQ/prism-control/ent/initiativedependency"
	"github.com/ProductBuildersHQ/prism-control/ent/phase"
	"github.com/ProductBuildersHQ/prism-control/ent/program"
	"github.com/ProductBuildersHQ/prism-control/ent/repository"
	"github.com/ProductBuildersHQ/prism-control/ent/repositorydependency"
	"github.com/ProductBuildersHQ/prism-control/ent/rmidependency"
	"github.com/ProductBuildersHQ/prism-control/ent/roadmapitem"
	"github.com/ProductBuildersHQ/prism-control/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	assignmentFields := schema.Assignment{}.Fields()
	_ = assignmentFields
	// assignmentDescWorker is the schema descriptor for worker field.
	assignmentDescWorker := assignmentFields[1].Descriptor()
	// assignment.WorkerValidator is a validator for the "worker" field. It is called by the builders before save.
	assignment.WorkerValidator = assignmentDescWorker.Validators[0].(func(string) error)
	// assignmentDescStatus is the schema descriptor for status field.
	assignmentDescStatus := assignmentFields[2].Descriptor()
	// assignment.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	assignment.StatusValidator = assignmentDescStatus.Validators[0].(func(string) error)
	// assignmentDescWorkspace is the schema descriptor for workspace field.
	assignmentDescWorkspace := assignmentFields[4].Descriptor()
	// assignment.WorkspaceValidator is a validator for the "workspace" field. It is called by the builders before save.
	assignment.WorkspaceValidator = assignmentDescWorkspace.Validators[0].(func(string) error)
	// assignmentDescID is the schema descriptor for id field.
	assignmentDescID := assignmentFields[0].Descriptor()
	// assignment.IDValidator is a validator for the "id" field. It is called by the builders before save.
	assignment.IDValidator = assignmentDescID.Validators[0].(func(string) error)
	deliveryevidenceFields := schema.DeliveryEvidence{}.Fields()
	_ = deliveryevidenceFields
	// deliveryevidenceDescEvidenceType is the schema descriptor for evidence_type field.
	deliveryevidenceDescEvidenceType := deliveryevidenceFields[1].Descriptor()
	// deliveryevidence.EvidenceTypeValidator is a validator for the "evidence_type" field. It is called by the builders before save.
	deliveryevidence.EvidenceTypeValidator = deliveryevidenceDescEvidenceType.Validators[0].(func(string) error)
	// deliveryevidenceDescReference is the schema descriptor for reference field.
	deliveryevidenceDescReference := deliveryevidenceFields[2].Descriptor()
	// deliveryevidence.ReferenceValidator is a validator for the "reference" field. It is called by the builders before save.
	deliveryevidence.ReferenceValidator = deliveryevidenceDescReference.Validators[0].(func(string) error)
	// deliveryevidenceDescCommitType is the schema descriptor for commit_type field.
	deliveryevidenceDescCommitType := deliveryevidenceFields[3].Descriptor()
	// deliveryevidence.CommitTypeValidator is a validator for the "commit_type" field. It is called by the builders before save.
	deliveryevidence.CommitTypeValidator = deliveryevidenceDescCommitType.Validators[0].(func(string) error)
	// deliveryevidenceDescCommitScope is the schema descriptor for commit_scope field.
	deliveryevidenceDescCommitScope := deliveryevidenceFields[4].Descriptor()
	// deliveryevidence.CommitScopeValidator is a validator for the "commit_scope" field. It is called by the builders before save.
	deliveryevidence.CommitScopeValidator = deliveryevidenceDescCommitScope.Validators[0].(func(string) error)
	// deliveryevidenceDescID is the schema descriptor for id field.
	deliveryevidenceDescID := deliveryevidenceFields[0].Descriptor()
	// deliveryevidence.IDValidator is a validator for the "id" field. It is called by the builders before save.
	deliveryevidence.IDValidator = deliveryevidenceDescID.Validators[0].(func(string) error)
	initiativeFields := schema.Initiative{}.Fields()
	_ = initiativeFields
	// initiativeDescOrganization is the schema descriptor for organization field.
	initiativeDescOrganization := initiativeFields[1].Descriptor()
	// initiative.OrganizationValidator is a validator for the "organization" field. It is called by the builders before save.
	initiative.OrganizationValidator = initiativeDescOrganization.Validators[0].(func(string) error)
	// initiativeDescTitle is the schema descriptor for title field.
	initiativeDescTitle := initiativeFields[2].Descriptor()
	// initiative.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	initiative.TitleValidator = initiativeDescTitle.Validators[0].(func(string) error)
	// initiativeDescStatus is the schema descriptor for status field.
	initiativeDescStatus := initiativeFields[4].Descriptor()
	// initiative.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	initiative.StatusValidator = initiativeDescStatus.Validators[0].(func(string) error)
	// initiativeDescInitType is the schema descriptor for init_type field.
	initiativeDescInitType := initiativeFields[5].Descriptor()
	// initiative.DefaultInitType holds the default value on creation for the init_type field.
	initiative.DefaultInitType = initiativeDescInitType.Default.(string)
	// initiative.InitTypeValidator is a validator for the "init_type" field. It is called by the builders before save.
	initiative.InitTypeValidator = initiativeDescInitType.Validators[0].(func(string) error)
	// initiativeDescWorkflowID is the schema descriptor for workflow_id field.
	initiativeDescWorkflowID := initiativeFields[6].Descriptor()
	// initiative.WorkflowIDValidator is a validator for the "workflow_id" field. It is called by the builders before save.
	initiative.WorkflowIDValidator = initiativeDescWorkflowID.Validators[0].(func(string) error)
	// initiativeDescPriority is the schema descriptor for priority field.
	initiativeDescPriority := initiativeFields[7].Descriptor()
	// initiative.PriorityValidator is a validator for the "priority" field. It is called by the builders before save.
	initiative.PriorityValidator = initiativeDescPriority.Validators[0].(func(string) error)
	// initiativeDescHomeRepo is the schema descriptor for home_repo field.
	initiativeDescHomeRepo := initiativeFields[8].Descriptor()
	// initiative.HomeRepoValidator is a validator for the "home_repo" field. It is called by the builders before save.
	initiative.HomeRepoValidator = initiativeDescHomeRepo.Validators[0].(func(string) error)
	// initiativeDescWorkspace is the schema descriptor for workspace field.
	initiativeDescWorkspace := initiativeFields[9].Descriptor()
	// initiative.WorkspaceValidator is a validator for the "workspace" field. It is called by the builders before save.
	initiative.WorkspaceValidator = initiativeDescWorkspace.Validators[0].(func(string) error)
	// initiativeDescID is the schema descriptor for id field.
	initiativeDescID := initiativeFields[0].Descriptor()
	// initiative.IDValidator is a validator for the "id" field. It is called by the builders before save.
	initiative.IDValidator = initiativeDescID.Validators[0].(func(string) error)
	initiativedependencyFields := schema.InitiativeDependency{}.Fields()
	_ = initiativedependencyFields
	// initiativedependencyDescSourceInitiativeID is the schema descriptor for source_initiative_id field.
	initiativedependencyDescSourceInitiativeID := initiativedependencyFields[0].Descriptor()
	// initiativedependency.SourceInitiativeIDValidator is a validator for the "source_initiative_id" field. It is called by the builders before save.
	initiativedependency.SourceInitiativeIDValidator = initiativedependencyDescSourceInitiativeID.Validators[0].(func(string) error)
	// initiativedependencyDescTargetInitiativeID is the schema descriptor for target_initiative_id field.
	initiativedependencyDescTargetInitiativeID := initiativedependencyFields[1].Descriptor()
	// initiativedependency.TargetInitiativeIDValidator is a validator for the "target_initiative_id" field. It is called by the builders before save.
	initiativedependency.TargetInitiativeIDValidator = initiativedependencyDescTargetInitiativeID.Validators[0].(func(string) error)
	// initiativedependencyDescRelationship is the schema descriptor for relationship field.
	initiativedependencyDescRelationship := initiativedependencyFields[2].Descriptor()
	// initiativedependency.RelationshipValidator is a validator for the "relationship" field. It is called by the builders before save.
	initiativedependency.RelationshipValidator = initiativedependencyDescRelationship.Validators[0].(func(string) error)
	phaseFields := schema.Phase{}.Fields()
	_ = phaseFields
	// phaseDescTitle is the schema descriptor for title field.
	phaseDescTitle := phaseFields[2].Descriptor()
	// phase.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	phase.TitleValidator = phaseDescTitle.Validators[0].(func(string) error)
	// phaseDescTheme is the schema descriptor for theme field.
	phaseDescTheme := phaseFields[3].Descriptor()
	// phase.ThemeValidator is a validator for the "theme" field. It is called by the builders before save.
	phase.ThemeValidator = phaseDescTheme.Validators[0].(func(string) error)
	// phaseDescID is the schema descriptor for id field.
	phaseDescID := phaseFields[0].Descriptor()
	// phase.IDValidator is a validator for the "id" field. It is called by the builders before save.
	phase.IDValidator = phaseDescID.Validators[0].(func(string) error)
	programFields := schema.Program{}.Fields()
	_ = programFields
	// programDescName is the schema descriptor for name field.
	programDescName := programFields[1].Descriptor()
	// program.NameValidator is a validator for the "name" field. It is called by the builders before save.
	program.NameValidator = programDescName.Validators[0].(func(string) error)
	// programDescOrganization is the schema descriptor for organization field.
	programDescOrganization := programFields[2].Descriptor()
	// program.OrganizationValidator is a validator for the "organization" field. It is called by the builders before save.
	program.OrganizationValidator = programDescOrganization.Validators[0].(func(string) error)
	// programDescHidden is the schema descriptor for hidden field.
	programDescHidden := programFields[4].Descriptor()
	// program.DefaultHidden holds the default value on creation for the hidden field.
	program.DefaultHidden = programDescHidden.Default.(bool)
	// programDescID is the schema descriptor for id field.
	programDescID := programFields[0].Descriptor()
	// program.IDValidator is a validator for the "id" field. It is called by the builders before save.
	program.IDValidator = programDescID.Validators[0].(func(string) error)
	rmidependencyFields := schema.RMIDependency{}.Fields()
	_ = rmidependencyFields
	// rmidependencyDescSourceRmiID is the schema descriptor for source_rmi_id field.
	rmidependencyDescSourceRmiID := rmidependencyFields[0].Descriptor()
	// rmidependency.SourceRmiIDValidator is a validator for the "source_rmi_id" field. It is called by the builders before save.
	rmidependency.SourceRmiIDValidator = rmidependencyDescSourceRmiID.Validators[0].(func(string) error)
	// rmidependencyDescTargetRmiID is the schema descriptor for target_rmi_id field.
	rmidependencyDescTargetRmiID := rmidependencyFields[1].Descriptor()
	// rmidependency.TargetRmiIDValidator is a validator for the "target_rmi_id" field. It is called by the builders before save.
	rmidependency.TargetRmiIDValidator = rmidependencyDescTargetRmiID.Validators[0].(func(string) error)
	// rmidependencyDescRelationship is the schema descriptor for relationship field.
	rmidependencyDescRelationship := rmidependencyFields[2].Descriptor()
	// rmidependency.RelationshipValidator is a validator for the "relationship" field. It is called by the builders before save.
	rmidependency.RelationshipValidator = rmidependencyDescRelationship.Validators[0].(func(string) error)
	repositoryFields := schema.Repository{}.Fields()
	_ = repositoryFields
	// repositoryDescOrganization is the schema descriptor for organization field.
	repositoryDescOrganization := repositoryFields[1].Descriptor()
	// repository.OrganizationValidator is a validator for the "organization" field. It is called by the builders before save.
	repository.OrganizationValidator = repositoryDescOrganization.Validators[0].(func(string) error)
	// repositoryDescRepositoryName is the schema descriptor for repository_name field.
	repositoryDescRepositoryName := repositoryFields[2].Descriptor()
	// repository.RepositoryNameValidator is a validator for the "repository_name" field. It is called by the builders before save.
	repository.RepositoryNameValidator = repositoryDescRepositoryName.Validators[0].(func(string) error)
	// repositoryDescDefaultBranch is the schema descriptor for default_branch field.
	repositoryDescDefaultBranch := repositoryFields[3].Descriptor()
	// repository.DefaultDefaultBranch holds the default value on creation for the default_branch field.
	repository.DefaultDefaultBranch = repositoryDescDefaultBranch.Default.(string)
	// repository.DefaultBranchValidator is a validator for the "default_branch" field. It is called by the builders before save.
	repository.DefaultBranchValidator = repositoryDescDefaultBranch.Validators[0].(func(string) error)
	// repositoryDescLocalPath is the schema descriptor for local_path field.
	repositoryDescLocalPath := repositoryFields[4].Descriptor()
	// repository.LocalPathValidator is a validator for the "local_path" field. It is called by the builders before save.
	repository.LocalPathValidator = repositoryDescLocalPath.Validators[0].(func(string) error)
	// repositoryDescGoModule is the schema descriptor for go_module field.
	repositoryDescGoModule := repositoryFields[5].Descriptor()
	// repository.GoModuleValidator is a validator for the "go_module" field. It is called by the builders before save.
	repository.GoModuleValidator = repositoryDescGoModule.Validators[0].(func(string) error)
	// repositoryDescDomain is the schema descriptor for domain field.
	repositoryDescDomain := repositoryFields[6].Descriptor()
	// repository.DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	repository.DomainValidator = repositoryDescDomain.Validators[0].(func(string) error)
	// repositoryDescStatus is the schema descriptor for status field.
	repositoryDescStatus := repositoryFields[7].Descriptor()
	// repository.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	repository.StatusValidator = repositoryDescStatus.Validators[0].(func(string) error)
	// repositoryDescIngestHighWater is the schema descriptor for ingest_high_water field.
	repositoryDescIngestHighWater := repositoryFields[8].Descriptor()
	// repository.IngestHighWaterValidator is a validator for the "ingest_high_water" field. It is called by the builders before save.
	repository.IngestHighWaterValidator = repositoryDescIngestHighWater.Validators[0].(func(string) error)
	// repositoryDescID is the schema descriptor for id field.
	repositoryDescID := repositoryFields[0].Descriptor()
	// repository.IDValidator is a validator for the "id" field. It is called by the builders before save.
	repository.IDValidator = repositoryDescID.Validators[0].(func(string) error)
	repositorydependencyFields := schema.RepositoryDependency{}.Fields()
	_ = repositorydependencyFields
	// repositorydependencyDescSourceRepositoryID is the schema descriptor for source_repository_id field.
	repositorydependencyDescSourceRepositoryID := repositorydependencyFields[0].Descriptor()
	// repositorydependency.SourceRepositoryIDValidator is a validator for the "source_repository_id" field. It is called by the builders before save.
	repositorydependency.SourceRepositoryIDValidator = repositorydependencyDescSourceRepositoryID.Validators[0].(func(string) error)
	// repositorydependencyDescTargetRepositoryID is the schema descriptor for target_repository_id field.
	repositorydependencyDescTargetRepositoryID := repositorydependencyFields[1].Descriptor()
	// repositorydependency.TargetRepositoryIDValidator is a validator for the "target_repository_id" field. It is called by the builders before save.
	repositorydependency.TargetRepositoryIDValidator = repositorydependencyDescTargetRepositoryID.Validators[0].(func(string) error)
	// repositorydependencyDescDependencyType is the schema descriptor for dependency_type field.
	repositorydependencyDescDependencyType := repositorydependencyFields[2].Descriptor()
	// repositorydependency.DependencyTypeValidator is a validator for the "dependency_type" field. It is called by the builders before save.
	repositorydependency.DependencyTypeValidator = repositorydependencyDescDependencyType.Validators[0].(func(string) error)
	roadmapitemFields := schema.RoadmapItem{}.Fields()
	_ = roadmapitemFields
	// roadmapitemDescTitle is the schema descriptor for title field.
	roadmapitemDescTitle := roadmapitemFields[1].Descriptor()
	// roadmapitem.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	roadmapitem.TitleValidator = roadmapitemDescTitle.Validators[0].(func(string) error)
	// roadmapitemDescItemType is the schema descriptor for item_type field.
	roadmapitemDescItemType := roadmapitemFields[3].Descriptor()
	// roadmapitem.ItemTypeValidator is a validator for the "item_type" field. It is called by the builders before save.
	roadmapitem.ItemTypeValidator = roadmapitemDescItemType.Validators[0].(func(string) error)
	// roadmapitemDescStatus is the schema descriptor for status field.
	roadmapitemDescStatus := roadmapitemFields[4].Descriptor()
	// roadmapitem.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	roadmapitem.StatusValidator = roadmapitemDescStatus.Validators[0].(func(string) error)
	// roadmapitemDescPriority is the schema descriptor for priority field.
	roadmapitemDescPriority := roadmapitemFields[5].Descriptor()
	// roadmapitem.PriorityValidator is a validator for the "priority" field. It is called by the builders before save.
	roadmapitem.PriorityValidator = roadmapitemDescPriority.Validators[0].(func(string) error)
	// roadmapitemDescRequired is the schema descriptor for required field.
	roadmapitemDescRequired := roadmapitemFields[6].Descriptor()
	// roadmapitem.DefaultRequired holds the default value on creation for the required field.
	roadmapitem.DefaultRequired = roadmapitemDescRequired.Default.(bool)
	// roadmapitemDescID is the schema descriptor for id field.
	roadmapitemDescID := roadmapitemFields[0].Descriptor()
	// roadmapitem.IDValidator is a validator for the "id" field. It is called by the builders before save.
	roadmapitem.IDValidator = roadmapitemDescID.Validators[0].(func(string) error)
}
