// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Assignment is the predicate function for assignment builders.
type Assignment func(*sql.Selector)

// DeliveryEvidence is the predicate function for deliveryevidence builders.
type DeliveryEvidence func(*sql.Selector)

// Initiative is the predicate function for initiative builders.
type Initiative func(*sql.Selector)

// InitiativeDependency is the predicate function for initiativedependency builders.
type InitiativeDependency func(*sql.Selector)

// Phase is the predicate function for phase builders.
type Phase func(*sql.Selector)

// Program is the predicate function for program builders.
type Program func(*sql.Selector)

// RMIDependency is the predicate function for rmidependency builders.
type RMIDependency func(*sql.Selector)

// Repository is the predicate function for repository builders.
type Repository func(*sql.Selector)

// RepositoryDependency is the predicate function for repositorydependency builders.
type RepositoryDependency func(*sql.Selector)

// RoadmapItem is the predicate function for roadmapitem builders.
type RoadmapItem func(*sql.Selector)
